### PR TITLE
Add support for null default value for nullable members of dictionaries.

### PR DESCRIPTION
**Pull request by marcinbak**
Added support for null default value for nullable members of dictionaries.

Change required to parse specification https://www.w3.org/TR/IndexedDB/#events

### CODE REVIEW

**Comment by Schahen** [comment]
Hey @marcinbak! Thank you for the PR. Can you please add also a test case - so that it would be self-evident what the PR is about.

**Comment by marcinbak** [comment]
@Schahen I wanted to write a unit test for that but couldn't find any in the project. In what form and where should this test case go?

**Comment by trilis** [comment]
Please add your test in form of *.webidl and *.d.kt files with matching names to https://github.com/Kotlin/dukat/tree/master/compiler/test/data/idl
You can then check if it passes by launching https://github.com/Kotlin/dukat/blob/master/compiler/test/src/org/jetbrains/dukat/compiler/tests/core/IdlTests.kt

**Comment by marcinbak** [comment]
Added tests to existing dictionary test cases so it's in one place. Hope that's ok.

**Comment by trilis** [comment]
Sure, LGTM. Thank you for your contribution!

**Pull request merged**
